import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import TransitionProvider from "@/components/transitionProvider";


export const metadata: Metadata = {
  title: "Souvik Sarkar Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="overflow-x-hidden">
        {/* Full Background */}
        <TransitionProvider>{children}</TransitionProvider>
      </body>
    </html>
  );
}
